// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "ed44ca82-b34b-476e-a677-a87cb865caa4";

const char SSID[] = SECRET_SSID;              // Network SSID (name)
const char PASS[] = SECRET_PASS;              // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;  // Secret device password

float temperatur = 0.0f;
float luftfeuchtigkeit = 0.0f;
float luftdruck = 0.0f;
float uvlicht = 0.0f;

void onValueChange();

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  
  ArduinoCloud.addProperty(temperatur, READWRITE, ON_CHANGE, onValueChange, 1);
  ArduinoCloud.addProperty(luftfeuchtigkeit, READWRITE, ON_CHANGE, onValueChange, 1);
  ArduinoCloud.addProperty(luftdruck, READWRITE, ON_CHANGE, onValueChange, 1);
  ArduinoCloud.addProperty(uvlicht, READWRITE, ON_CHANGE, onValueChange, 1);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);